### ISSUE TITLE
Gzip payload

### ISSUE THREAD

**Issue by mestroma** [mmarinm/sumologrus#4]
Gzip payload before uploading to Sumo

**Comment by vigneshashokan** [comment]
@mmarinm If no one is working on this, I can take a stab at this issue.

**Comment by mestroma** [comment]
@vigneshashokan please feel free to help.  This is was done is rush last week it is still in alpha phase and there is no other contributors beside me, any help is welcome.  Just please don't use it in production yet, once I test it sufficiently I'll update the release to beta.

**Comment by mestroma** [comment]
@vigneshashokan  I fixed all of the issues with concurrency and released stable version that can be used in prod, you can pool latest changes.

**Comment by vigneshashokan** [comment]
Hey @mmarinm, sorry for the late reply. I created a PR for this https://github.com/mmarinm/sumologrus/pull/13. Let me know what you think.

**Comment by mestroma** [comment]
thanks for PR
